# Case Study on Testing of Hypothesis

A company started to invest in digital marketing as a new way of their product promotions. For that they collected data and decided to carry out a study on it:

 1.The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.
 2.The company needs to check whether there is any dependency between the features “Region” and “Manager”.

Help the company to carry out their study with the help of data provided.


In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from statsmodels.stats import weightstats as stests
data = pd.read_csv("Sales_add.csv")
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [29]:
data.isnull().sum().sum()

0

## The company wishes to clarify whether there is any increase in sales after stepping into digital marketing

In [6]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

In [7]:
d1=data.groupby('Region',as_index=False).sum()
d1

Region  Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
0  Region - A                         1482049                        2388531
1  Region - B                         1053665                        1601095
2  Region - C                          747565                        1095096

#### The mean and standard deviation of sales before digital and after the digital is increased.

#### H0:There is no diffrence in sales after digital marketing

#### H1:There is an increase in sales after digital marketing

In [13]:
#Paired sampled t-test
ttest,pval = stats.ttest_rel(data['Sales_before_digital_add(in $)'], data['Sales_After_digital_add(in $)'])
print(pval)
if pval<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

6.336667004575778e-11
reject null hypothesis


## The company needs to check whether there is any dependency between the features "Region" and "Manager".

In [24]:
## contingency table between region and manager.
pd.crosstab(data.Region, data.Manager)

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [25]:
## loading chi2_contingency
from scipy.stats import chi2_contingency

In [26]:
chi, p, dof, expected = chi2_contingency(pd.crosstab(data.Region, data.Manager))

In [27]:
## the test statistic.
print(chi)
## degree of freedom
print(dof)
## expected frequencies
print(expected)
## p value
print(p)

3.050566893424036
4
[[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
0.5493991051158094


####  Since the P-value is > 0.05 we can accept the null hypothesis So we can say that they are independent.